-- 코드를 입력하세요
SELECT A.APNT_NO AS APNT_NO, P.PT_NAME AS PT_NAME, A.PT_NO AS PT_NO, A.MCDP_CD AS MCDP_CD, D.DR_NAME AS DR_NAME, A.APNT_YMD AS APNT_YMD
FROM PATIENT AS P, DOCTOR AS D, APPOINTMENT AS A
WHERE A.PT_NO = P.PT_NO AND A.MDDR_ID = D.DR_ID
AND DATE_FORMAT(A.APNT_YMD,'%Y-%m-%d') LIKE '2022-04-13'
AND A.APNT_CNCL_YN = 'N'
AND A.MCDP_CD = 'CS'
ORDER BY A.APNT_YMD