SELECT ITEM_INFO.ITEM_ID AS ITEM_ID, 
                ITEM_INFO.ITEM_NAME AS ITEM_NAME, 
                ITEM_INFO.RARITY AS RARITY
FROM ITEM_INFO JOIN ITEM_TREE 
ON ITEM_INFO.ITEM_ID = ITEM_TREE.ITEM_ID
WHERE ITEM_TREE.PARENT_ITEM_ID IN (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = 'RARE')
ORDER BY ITEM_ID DESC;


# SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY
# FROM ITEM_INFO A INNER JOIN ITEM_TREE B
# ON A.ITEM_ID = B.ITEM_ID
# WHERE B.PARENT_ITEM_ID IN (SELECT A.ITEM_ID
#                            FROM ITEM_INFO A INNER JOIN ITEM_TREE B
#                            ON A.ITEM_ID = B.ITEM_ID
#                            WHERE A.RARITY LIKE 'RARE')
# ORDER BY A.ITEM_ID DESC;