-- 코드를 입력하세요
SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(BS.SALES * B.PRICE) TOTAL_SALE
FROM BOOK AS B, AUTHOR AS A, BOOK_SALES AS BS
WHERE B.AUTHOR_ID = A.AUTHOR_ID AND B.BOOK_ID = BS.BOOK_ID AND BS.SALES_DATE LIKE '2022-01%'
GROUP BY B.AUTHOR_ID, B.CATEGORY
ORDER BY B.AUTHOR_ID, B.CATEGORY DESC


# SELECT
# b.AUTHOR_ID,
# a.AUTHOR_NAME,
# b.CATEGORY,
# SUM(bs.SALES * b.PRICE) TOTAL_SALES
# FROM
# BOOK_SALES bs 
# JOIN BOOK b
# ON bs.BOOK_ID = b.BOOK_ID
# JOIN AUTHOR a
# ON b.AUTHOR_ID = a.AUTHOR_ID
# WHERE bs.SALES_DATE BETWEEN "2022-01-01" AND "2022-01-31"
# GROUP BY b.AUTHOR_ID, b.CATEGORY
# ORDER BY b.AUTHOR_ID, b.CATEGORY DESC;