SELECT DISTINCT CC.CAR_ID AS CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS CC, CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CH
WHERE CC.CAR_ID = CH.CAR_ID 
AND CC.CAR_TYPE = '세단'
AND CH.START_DATE LIKE "%-10-%"
ORDER BY CC.CAR_ID DESC